### ISSUE TITLE
Update browser support 

### ISSUE THREAD

**Issue by sergioisidoro** [django-master/django-webp#33]
Right now this only supports 
```

WEBP_VALID_BROWSERS = getattr(settings, 'WEBP_VALID_BROWSERS', ['Chrome', 'Opera', 'Opera Mobile'])
```

However most browsers (except IE) now support WEBP. Should this check be entirely removed?

**Comment by bimmui** [comment]
Since all browser minus IE support WEBP and IE was retired as of last year, we removed any sort of browser checking from `context_processor.py`.
