### ISSUE TITLE
Upload Latest Version To PyPi & Update Docs With New Feature Usage

### ISSUE THREAD

**Issue by 9mido** [django-master/django-webp#7]
Thank you for your most recent changes. Wondering when this will show up on PyPi? And also how to use the new media folder / URL features? (would love if issue 9 was included in the new version)

**Comment by andrefarzat** [comment]
I just published the version `2.0.0` with python3 and django 3 support.

The media folder / url, as I was trying in https://github.com/andrefarzat/django-webp/issues/3, I could manage to make it work properly, for the media is informed via url, while the static file are informed as path, thus I can access the latter in the disc and the media url no.

What I think we can do is to check if the given path is a url. If yes, we download the image, convert to webp, cache it, and then serve it. But this create other kind of problems. The first I can imagine is cache/disk space, for it would be impossible to determine when to *not* download and cache an image to avoid explode the disk.

What do you think ?

**Comment by 9mido** [comment]
Awesome thank you for the quick responses and code changes to these issues! 

Hmm good points especially on the filling up of disk space. That is definitely a concern and should be avoided. Unless maybe you could have a cron job run and delete the cache / disk space? But I imagine lots of visitors will create a lot of disk file save entries and I wonder if it will be hard for a cron job to keep up? Or I wonder if you could store in the session instead of the disk then when the session closes delete it? 

You mean check if path project_name/media/image.png is also a url 127.0.0.1:8000/media/image.png then convert the url to 127.0.0.1:8000/media/image.webp and save in project_name/media/image.webp? 

What if the media disk path is the same as the url media path? That is how my project is currently set up (like shown in the above paragraph). But other users of this package might be set up differently.
