### ISSUE TITLE
Convert From Webp To Another Format?

### ISSUE THREAD

**Issue by 9mido** [django-master/django-webp#9]
If my site uses webp by default, it would be nice for there to be a way to convert to another format if the browser does not support it. Is this currently a feature or can this possibly be worked on?

`<img src="/media/test.webp" alt="alt" width="500" height="300">`

Becomes 

```
<img src="/media/test.png" alt="alt" width="500" height="300">
<img src="/media/test.jpeg" alt="alt" width="500" height="300">
```

**Comment by andrefarzat** [comment]
This is an interesting idea. You think we could use the same templatetag? 
We could add a settings (say `WEBP_FALLBACK_TO = 'png'`).

What do you think ?

**Comment by 9mido** [comment]
Yay glad you think it is a great idea! I like the way you implemented it. Seems easier to just use a setting and the same template tag.

**Comment by 9mido** [comment]
@andrefarzat 

Maybe this can help you do it. 

https://medium.com/@ajeetham/image-type-conversion-jpg-png-jpg-webp-png-webp-with-python-7d5df09394c9
